version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
    restart: always
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    #ports:
    #  - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always
    env_file:
       - .env

# Bonuses

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    ports:
      - 6379:6379
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
    restart: always
    env_file:
      - .env

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hlibine/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hlibine/data/mariadb


networks:
  network:
    driver: bridge
