version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - /home/hlibine/data/wordpress:/var/www/html
    networks:
      - network
    restart: always

    wordpress:
      container_name: wordpress
      build: ./requirements/wordpress
      depends_on:
        - mariadb
      volumes:
        - /home/hlibine/data/wordpress:/var/www/html
      networks:
          - network
      restart: always
      env_file:
        - .env

#  mariadb:
#    container_name: mariadb
#    build: ./requirements/mariadb
#    volumes:
#      - mariadb_data:/var/lib/mysql
#    networks:
#      - network
#    restart: always
#    env_file:
#      - .env

    #volumes:
    #  wordpress_data:
    #    driver: local
    #    driver_opts:
    #      type: none
    #      device: /home/hlibine/data/wordpress
    #      o: bind

networks:
  network:
    driver: bridge
