version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports: 443
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
    restart: always


#  mariadb:
#    container_name: mariadb
#    build: ./requirements/mariadb
#    volumes:
#      - mariadb_data:/var/lib/mysql
#    networks:
#      - network
#    restart: always
#    env_file:
#      - .env

    volumes:
      wordpress_data:
        driver: local
        driver_opts:
          type: none
          device: /home/hlibine/data/wordpress
          o: bind

    networks:
      network:
        driver: bridge
