services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - 9000:9000
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
    restart: always
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: always
    env_file:
       - .env

# Bonuses

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    ports:
      - 6379:6379
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
    restart: always
    env_file:
      - .env

  static-page:
    container_name: static-page
    build: ./requirements/bonus/static_page
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - nginx

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/mariadb


networks:
  network:
    driver: bridge
